# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/110LH0DmZvERf4BRD9lSyBZ8TOK6IyLdd
"""

import streamlit as st
import pandas as pd
from google.cloud import bigquery
from datetime import date

# =========================
# CONFIG
# =========================
st.set_page_config(
    page_title="Chexy Daily Health",
    layout="wide",
)

# =========================
# BIGQUERY – SINGLE SUPER QUERY
# =========================
# ⚠️ Replace the string below with the final unified query I will generate for you next.

QUERY = """
-- ===============================================================
-- SUPER QUERY: ALL MARKETING KPIs IN ONE QUERY
--  - Active Users 30d / 60d / 90d
--  - New Accounts (Today / WTD / MTD)
--  - New Activations (Today / WTD / MTD)
-- Output shape (for Streamlit app.py):
--   segment | metric_name | current_value | previous_value | absolute_change | percent_change
-- ===============================================================

WITH
-- ===============================================================
-- USER SEGMENTATION (Consumer vs SMB)
-- ===============================================================
users_clean AS (
  SELECT
    document_id AS user_id,
    CASE
      WHEN LOWER(TRIM(JSON_EXTRACT_SCALAR(data, '$.is_smb'))) = 'true' THEN 'SMB'
      ELSE 'Consumer'
    END AS segment,
    TIMESTAMP_SECONDS(SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.created_at._seconds') AS INT64)) AS created_at,
    TIMESTAMP_SECONDS(SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.activation_date._seconds') AS INT64)) AS activation_date,
    ROW_NUMBER() OVER (
      PARTITION BY document_id
      ORDER BY TIMESTAMP_SECONDS(SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.updated_at._seconds') AS INT64)) DESC
    ) AS rn
  FROM `chexy-core.users.users_raw_latest`
),
users AS (
  SELECT * FROM users_clean WHERE rn = 1
),

-- ===============================================================
-- SUBSCRIPTIONS (CURRENT + HISTORICAL SNAPSHOTS)
-- ===============================================================
subs_current AS (
  SELECT
    REPLACE(JSON_EXTRACT_SCALAR(data, '$.user_id'), '"', '') AS user_id,
    JSON_EXTRACT_SCALAR(data, '$.status') AS status,
    JSON_EXTRACT_SCALAR(data, '$.frequency') AS frequency
  FROM `chexy-core.firestore_export.posts_raw_latest`
),

subs_prev_base AS (
  SELECT
    REPLACE(JSON_EXTRACT_SCALAR(data, '$.user_id'), '"', '') AS user_id,
    document_id AS subscription_id,
    JSON_EXTRACT_SCALAR(data, '$.status') AS status,
    JSON_EXTRACT_SCALAR(data, '$.frequency') AS frequency,
    TIMESTAMP_SECONDS(SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.updated_at._seconds') AS INT64)) AS updated_at
  FROM `chexy-core.firestore_export.posts_raw_changelog`
),

-- snapshot as of 30 days ago
subs_prev_30 AS (
  SELECT
    user_id,
    subscription_id,
    status,
    frequency,
    updated_at,
    ROW_NUMBER() OVER (
      PARTITION BY subscription_id
      ORDER BY updated_at DESC
    ) AS rn
  FROM subs_prev_base
  WHERE updated_at <= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 30 DAY)
),
subs_prev_30_filtered AS (
  SELECT user_id, subscription_id, status, frequency
  FROM subs_prev_30
  WHERE rn = 1
),

-- snapshot as of 60 days ago
subs_prev_60 AS (
  SELECT
    user_id,
    subscription_id,
    status,
    frequency,
    updated_at,
    ROW_NUMBER() OVER (
      PARTITION BY subscription_id
      ORDER BY updated_at DESC
    ) AS rn
  FROM subs_prev_base
  WHERE updated_at <= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 60 DAY)
),
subs_prev_60_filtered AS (
  SELECT user_id, subscription_id, status, frequency
  FROM subs_prev_60
  WHERE rn = 1
),

-- snapshot as of 90 days ago
subs_prev_90 AS (
  SELECT
    user_id,
    subscription_id,
    status,
    frequency,
    updated_at,
    ROW_NUMBER() OVER (
      PARTITION BY subscription_id
      ORDER BY updated_at DESC
    ) AS rn
  FROM subs_prev_base
  WHERE updated_at <= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 90 DAY)
),
subs_prev_90_filtered AS (
  SELECT user_id, subscription_id, status, frequency
  FROM subs_prev_90
  WHERE rn = 1
),

-- ===============================================================
-- TRANSACTIONS (ONE-TIME USERS)
-- ===============================================================
tx_all AS (
  SELECT
    REPLACE(JSON_EXTRACT_SCALAR(data, '$.user_id'), '"', '') AS user_id,
    TIMESTAMP_SECONDS(SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.created_at._seconds') AS INT64)) AS txn_ts
  FROM `chexy-core.transactions.transactions_raw_latest`
  WHERE JSON_VALUE(data, '$.transaction_type') IN ('ACCOUNTS_RECEIVABLE', 'TRANSACTION_FEE')
    AND JSON_VALUE(data, '$.status') = 'COMPLETED'
),

-- windows for one-time current vs previous
tx_30_curr AS (
  SELECT * FROM tx_all
  WHERE txn_ts >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 30 DAY)
),
tx_30_prev AS (
  SELECT * FROM tx_all
  WHERE txn_ts >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 60 DAY)
    AND txn_ts < TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 30 DAY)
),

tx_60_curr AS (
  SELECT * FROM tx_all
  WHERE txn_ts >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 60 DAY)
),
tx_60_prev AS (
  SELECT * FROM tx_all
  WHERE txn_ts >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 120 DAY)
    AND txn_ts < TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 61 DAY)
),

tx_90_curr AS (
  SELECT * FROM tx_all
  WHERE txn_ts >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 90 DAY)
),
tx_90_prev AS (
  SELECT * FROM tx_all
  WHERE txn_ts >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 180 DAY)
    AND txn_ts < TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 91 DAY)
),

-- ===============================================================
-- ACTIVE USERS 30D
-- ===============================================================
active30_current_users AS (
  -- Recurring: ACTIVE today (frequency != ONE_TIME)
  SELECT DISTINCT u.segment, s.user_id
  FROM subs_current s
  JOIN users u ON u.user_id = s.user_id
  WHERE s.frequency != 'ONE_TIME'
    AND s.status = 'ACTIVE'

  UNION DISTINCT

  -- One-time: transaction in last 30 days AND ONE_TIME sub (ACTIVE/CLOSED)
  SELECT DISTINCT u.segment, t.user_id
  FROM tx_30_curr t
  JOIN subs_current s
    ON s.user_id = t.user_id
   AND s.frequency = 'ONE_TIME'
   AND s.status IN ('ACTIVE', 'CLOSED')
  JOIN users u ON u.user_id = t.user_id
),
active30_previous_users AS (
  -- Recurring: ACTIVE as of 30 days ago snapshot
  SELECT DISTINCT u.segment, s.user_id
  FROM subs_prev_30_filtered s
  JOIN users u ON u.user_id = s.user_id
  WHERE s.frequency != 'ONE_TIME'
    AND s.status = 'ACTIVE'

  UNION DISTINCT

  -- One-time: transaction 31–60 days ago & ONE_TIME sub in snapshot
  SELECT DISTINCT u.segment, t.user_id
  FROM tx_30_prev t
  JOIN subs_prev_30_filtered s
    ON s.user_id = t.user_id
   AND s.frequency = 'ONE_TIME'
   AND s.status IN ('ACTIVE', 'CLOSED')
  JOIN users u ON u.user_id = t.user_id
),
active30_current_agg AS (
  SELECT
    segment,
    COUNT(DISTINCT user_id) AS curr_count
  FROM active30_current_users
  GROUP BY segment
),
active30_previous_agg AS (
  SELECT
    segment,
    COUNT(DISTINCT user_id) AS prev_count
  FROM active30_previous_users
  GROUP BY segment
),
active30 AS (
  SELECT
    COALESCE(c.segment, p.segment) AS segment,
    'active_users_30d' AS metric_name,
    COALESCE(c.curr_count, 0) AS current_value,
    COALESCE(p.prev_count, 0) AS previous_value
  FROM active30_current_agg c
  FULL OUTER JOIN active30_previous_agg p
    ON c.segment = p.segment
),

-- ===============================================================
-- ACTIVE USERS 60D
-- ===============================================================
active60_current_users AS (
  -- Recurring: ACTIVE today
  SELECT DISTINCT u.segment, s.user_id
  FROM subs_current s
  JOIN users u ON u.user_id = s.user_id
  WHERE s.frequency != 'ONE_TIME'
    AND s.status = 'ACTIVE'

  UNION DISTINCT

  -- One-time: transaction in last 60 days & ONE_TIME sub
  SELECT DISTINCT u.segment, t.user_id
  FROM tx_60_curr t
  JOIN subs_current s
    ON s.user_id = t.user_id
   AND s.frequency = 'ONE_TIME'
   AND s.status IN ('ACTIVE', 'CLOSED')
  JOIN users u ON u.user_id = t.user_id
),
active60_previous_users AS (
  -- Recurring: ACTIVE as of 60 days ago snapshot
  SELECT DISTINCT u.segment, s.user_id
  FROM subs_prev_60_filtered s
  JOIN users u ON u.user_id = s.user_id
  WHERE s.frequency != 'ONE_TIME'
    AND s.status = 'ACTIVE'

  UNION DISTINCT

  -- One-time: transaction 61–120 days ago & ONE_TIME sub in snapshot
  SELECT DISTINCT u.segment, t.user_id
  FROM tx_60_prev t
  JOIN subs_prev_60_filtered s
    ON s.user_id = t.user_id
   AND s.frequency = 'ONE_TIME'
   AND s.status IN ('ACTIVE', 'CLOSED')
  JOIN users u ON u.user_id = t.user_id
),
active60_current_agg AS (
  SELECT
    segment,
    COUNT(DISTINCT user_id) AS curr_count
  FROM active60_current_users
  GROUP BY segment
),
active60_previous_agg AS (
  SELECT
    segment,
    COUNT(DISTINCT user_id) AS prev_count
  FROM active60_previous_users
  GROUP BY segment
),
active60 AS (
  SELECT
    COALESCE(c.segment, p.segment) AS segment,
    'active_users_60d' AS metric_name,
    COALESCE(c.curr_count, 0) AS current_value,
    COALESCE(p.prev_count, 0) AS previous_value
  FROM active60_current_agg c
  FULL OUTER JOIN active60_previous_agg p
    ON c.segment = p.segment
),

-- ===============================================================
-- ACTIVE USERS 90D
-- ===============================================================
active90_current_users AS (
  -- Recurring: ACTIVE today
  SELECT DISTINCT u.segment, s.user_id
  FROM subs_current s
  JOIN users u ON u.user_id = s.user_id
  WHERE s.frequency != 'ONE_TIME'
    AND s.status = 'ACTIVE'

  UNION DISTINCT

  -- One-time: transaction in last 90 days & ONE_TIME sub
  SELECT DISTINCT u.segment, t.user_id
  FROM tx_90_curr t
  JOIN subs_current s
    ON s.user_id = t.user_id
   AND s.frequency = 'ONE_TIME'
   AND s.status IN ('ACTIVE', 'CLOSED')
  JOIN users u ON u.user_id = t.user_id
),
active90_previous_users AS (
  -- Recurring: ACTIVE as of 90 days ago snapshot
  SELECT DISTINCT u.segment, s.user_id
  FROM subs_prev_90_filtered s
  JOIN users u ON u.user_id = s.user_id
  WHERE s.frequency != 'ONE_TIME'
    AND s.status = 'ACTIVE'

  UNION DISTINCT

  -- One-time: transaction 91–180 days ago & ONE_TIME sub in snapshot
  SELECT DISTINCT u.segment, t.user_id
  FROM tx_90_prev t
  JOIN subs_prev_90_filtered s
    ON s.user_id = t.user_id
   AND s.frequency = 'ONE_TIME'
   AND s.status IN ('ACTIVE', 'CLOSED')
  JOIN users u ON u.user_id = t.user_id
),
active90_current_agg AS (
  SELECT
    segment,
    COUNT(DISTINCT user_id) AS curr_count
  FROM active90_current_users
  GROUP BY segment
),
active90_previous_agg AS (
  SELECT
    segment,
    COUNT(DISTINCT user_id) AS prev_count
  FROM active90_previous_users
  GROUP BY segment
),
active90 AS (
  SELECT
    COALESCE(c.segment, p.segment) AS segment,
    'active_users_90d' AS metric_name,
    COALESCE(c.curr_count, 0) AS current_value,
    COALESCE(p.prev_count, 0) AS previous_value
  FROM active90_current_agg c
  FULL OUTER JOIN active90_previous_agg p
    ON c.segment = p.segment
),

-- ===============================================================
-- NEW ACCOUNTS (CREATED_AT) – TODAY / WTD / MTD
-- ===============================================================
new_accounts_base AS (
  SELECT
    segment,
    DATE(created_at) AS created_date
  FROM users
  WHERE created_at IS NOT NULL
),

new_accounts_today AS (
  SELECT
    segment,
    'new_accounts_today' AS metric_name,
    COUNTIF(created_date = CURRENT_DATE()) AS current_value,
    COUNTIF(created_date = DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)) AS previous_value
  FROM new_accounts_base
  GROUP BY segment
),

new_accounts_wtd AS (
  SELECT
    segment,
    'new_accounts_wtd' AS metric_name,
    COUNTIF(created_date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 7 DAY) AND CURRENT_DATE()) AS current_value,
    COUNTIF(created_date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 14 DAY) AND DATE_SUB(CURRENT_DATE(), INTERVAL 7 DAY)) AS previous_value
  FROM new_accounts_base
  GROUP BY segment
),

new_accounts_mtd AS (
  SELECT
    segment,
    'new_accounts_mtd' AS metric_name,
    COUNTIF(created_date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 30 DAY) AND CURRENT_DATE()) AS current_value,
    COUNTIF(created_date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 60 DAY) AND DATE_SUB(CURRENT_DATE(), INTERVAL 30 DAY)) AS previous_value
  FROM new_accounts_base
  GROUP BY segment
),

-- ===============================================================
-- NEW ACTIVATIONS (ACTIVATION_DATE) – TODAY / WTD / MTD
-- ===============================================================
new_activations_base AS (
  SELECT
    segment,
    DATE(activation_date) AS act_date
  FROM users
  WHERE activation_date IS NOT NULL
),

new_activations_today AS (
  SELECT
    segment,
    'new_activations_today' AS metric_name,
    COUNTIF(act_date = CURRENT_DATE()) AS current_value,
    COUNTIF(act_date = DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)) AS previous_value
  FROM new_activations_base
  GROUP BY segment
),

new_activations_wtd AS (
  SELECT
    segment,
    'new_activations_wtd' AS metric_name,
    COUNTIF(act_date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 7 DAY) AND CURRENT_DATE()) AS current_value,
    COUNTIF(act_date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 14 DAY) AND DATE_SUB(CURRENT_DATE(), INTERVAL 7 DAY)) AS previous_value
  FROM new_activations_base
  GROUP BY segment
),

new_activations_mtd AS (
  SELECT
    segment,
    'new_activations_mtd' AS metric_name,
    COUNTIF(act_date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 30 DAY) AND CURRENT_DATE()) AS current_value,
    COUNTIF(act_date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 60 DAY) AND DATE_SUB(CURRENT_DATE(), INTERVAL 30 DAY)) AS previous_value
  FROM new_activations_base
  GROUP BY segment
),

-- ===============================================================
-- UNION ALL METRICS + CHANGE CALC
-- ===============================================================
full_metrics AS (
  SELECT * FROM active30
  UNION ALL SELECT * FROM active60
  UNION ALL SELECT * FROM active90
  UNION ALL SELECT * FROM new_accounts_today
  UNION ALL SELECT * FROM new_accounts_wtd
  UNION ALL SELECT * FROM new_accounts_mtd
  UNION ALL SELECT * FROM new_activations_today
  UNION ALL SELECT * FROM new_activations_wtd
  UNION ALL SELECT * FROM new_activations_mtd
),

final_output AS (
  SELECT
    segment,
    metric_name,
    current_value,
    previous_value,
    (current_value - previous_value) AS absolute_change,
    CASE
      WHEN previous_value = 0 THEN NULL
      ELSE ROUND((current_value - previous_value) / previous_value * 100, 1)
    END AS percent_change
  FROM full_metrics
)

SELECT *
FROM final_output
ORDER BY metric_name, segment;
"""


# =========================
# BIGQUERY LOADER
# =========================
@st.cache_data(ttl=300)
def load_metrics():
    client = bigquery.Client(project="chexy-core")
    df = client.query(QUERY).to_dataframe()
    return df


# =========================
# HELPER FUNCTIONS
# =========================

def summarize_metric(df, metric_name):
    """
    Takes the unified df and extracts one metric total for all segments.
    Example metric_name:
      'active_users_30d'
      'new_accounts_today'
    """
    subset = df[df["metric_name"] == metric_name]

    if subset.empty:
        return 0, 0, 0, None

    curr = subset["current_value"].sum()
    prev = subset["previous_value"].sum()
    abs_change = curr - prev

    if prev == 0:
        pct = None
    else:
        pct = round((abs_change / prev) * 100, 1)

    return curr, prev, abs_change, pct


def style_delta(abs_change, pct_change):
    if pct_change is None:
        return "—"
    arrow = "⬆️" if abs_change >= 0 else "⬇️"
    return f"{arrow} {abs_change:+,} ({pct_change:+}%)"


# =========================
# LOAD DATA
# =========================
st.title("Chexy Daily Health Dashboard")
st.caption(f"Snapshot as of {date.today().isoformat()}")

with st.spinner("Loading live metrics from BigQuery…"):
    df = load_metrics()

st.markdown("---")

# =========================
# ACTIVE USERS SECTION
# =========================
st.subheader("Active Users")

a30_curr, a30_prev, a30_abs, a30_pct = summarize_metric(df, "active_users_30d")
a60_curr, a60_prev, a60_abs, a60_pct = summarize_metric(df, "active_users_60d")
a90_curr, a90_prev, a90_abs, a90_pct = summarize_metric(df, "active_users_90d")

col1, col2, col3 = st.columns(3)

with col1:
    st.metric("30D Active Users (Total)", f"{a30_curr:,}", style_delta(a30_abs, a30_pct))

with col2:
    st.metric("60D Active Users (Total)", f"{a60_curr:,}", style_delta(a60_abs, a60_pct))

with col3:
    st.metric("90D Active Users (Total)", f"{a90_curr:,}", style_delta(a90_abs, a90_pct))

# ---- Active Users Segment Breakdown ----
st.markdown("#### Active Users by Segment")

active_seg = df[df["metric_name"].isin([
    "active_users_30d", "active_users_60d", "active_users_90d"
])]

pivot_active = active_seg.pivot(
    index="segment",
    columns="metric_name",
    values="current_value"
)

st.dataframe(pivot_active, use_container_width=True)
st.bar_chart(pivot_active)

st.markdown("---")

# =========================
# NEW ACCOUNTS SECTION
# =========================
st.subheader("New Accounts")
nt_curr, nt_prev, nt_abs, nt_pct = summarize_metric(df, "new_accounts_today")
nw_curr, nw_prev, nw_abs, nw_pct = summarize_metric(df, "new_accounts_wtd")
nm_curr, nm_prev, nm_abs, nm_pct = summarize_metric(df, "new_accounts_mtd")

c1, c2, c3 = st.columns(3)

with c1:
    st.metric("New Accounts – Today", f"{nt_curr:,}", style_delta(nt_abs, nt_pct))

with c2:
    st.metric("New Accounts – WTD", f"{nw_curr:,}", style_delta(nw_abs, nw_pct))

with c3:
    st.metric("New Accounts – MTD", f"{nm_curr:,}", style_delta(nm_abs, nm_pct))

# ---- New Accounts Breakdown ----
st.markdown("#### New Accounts by Segment")

new_seg = df[df["metric_name"].isin([
    "new_accounts_today", "new_accounts_wtd", "new_accounts_mtd"
])]

pivot_new = new_seg.pivot(
    index="segment",
    columns="metric_name",
    values="current_value"
)

st.dataframe(pivot_new, use_container_width=True)
st.bar_chart(pivot_new)

st.markdown("---")

# =========================
# NEW ACTIVATIONS SECTION
# =========================
st.subheader("New Activations")

at_curr, at_prev, at_abs, at_pct = summarize_metric(df, "new_activations_today")
aw_curr, aw_prev, aw_abs, aw_pct = summarize_metric(df, "new_activations_wtd")
am_curr, am_prev, am_abs, am_pct = summarize_metric(df, "new_activations_mtd")

d1, d2, d3 = st.columns(3)

with d1:
    st.metric("New Activations – Today", f"{at_curr:,}", style_delta(at_abs, at_pct))

with d2:
    st.metric("New Activations – WTD", f"{aw_curr:,}", style_delta(aw_abs, aw_pct))

with d3:
    st.metric("New Activations – MTD", f"{am_curr:,}", style_delta(am_abs, am_pct))

# ---- New Activations Breakdown ----
st.markdown("#### New Activations by Segment")

act_seg = df[df["metric_name"].isin([
    "new_activations_today", "new_activations_wtd", "new_activations_mtd"
])]

pivot_act = act_seg.pivot(
    index="segment",
    columns="metric_name",
    values="current_value"
)

st.dataframe(pivot_act, use_container_width=True)
st.bar_chart(pivot_act)

st.markdown("---")